### ISSUE TITLE
First start app with error

### ISSUE THREAD

**Issue by alekons** [Mamiglia/Reddit-Wallpaper#6]
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.logging/java.util.logging.Logger.addHandler(Logger.java:2060)
	at Utils.DisplayLogger.getInstance(DisplayLogger.java:38)
	at Main.Main.<clinit>(Main.java:13)
	... 7 more

**Comment by Mamiglia** [comment]
Does this error repeats? Is the program installed in the default directory?

**Comment by Mamiglia** [comment]
Due to no further response I'm closing this issue

**Comment by begundal** [comment]
This error occurs everytime I launched the program
![image](https://user-images.githubusercontent.com/342539/167983770-749a2de3-013e-4136-add0-560034e21a23.png)
the program installed at C:\ProgramData\Reddit-Wallpaper
